// <auto-generated />
using System;
using EFCoreConsoleApp2.DAL.Contextasdas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreConsoleApp2.DAL.Migrations345432234
{
    [DbContext(typeof(MyDbContextassd))]
    [Migration("20230803135155_asdsadsadasdasadasdasd")]
    partial class asdsadsadasdasadasdasd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("EFCoreConsoleApp2.DAL.Migrations345432234.Sample1", b =>
                {
                    b.Property<long?>("Lolo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lolo");

                    b.ToTable("sample_1", (string)null);
                });

            modelBuilder.Entity("EFCoreConsoleApp2.DAL.Migrations345432234.Sample2", b =>
                {
                    b.Property<long?>("Keke")
                        .HasColumnType("INTEGER")
                        .HasColumnName("keke");

                    b.ToTable("sample_2", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
