name: 'Close stale issues'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          debug-only: true
          exempt-draft-pr: true
          only-labels: 'waiting-for-info'
          stale-issue-message: 'This issue is stale because it has been open 14 days with no requested info. The issue will be automatically closed in 1 day.'
          close-issue-message: 'This issue was closed because it has been stalled for 1 day with no activity.'
          days-before-stale: 14
          days-before-close: 1
          days-before-pr-close: -1